COOLSITE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('dashboard.urls'), name='home'),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'), name='polls'),
    path('blogs/', include('blogs.urls'), name='blogs'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                           document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path
from . import views
app_name = 'blogs'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:Blog_id>/', views.detail, name='detail'),
    path('create', views.create, name='create'),
    path('success_saved', views.success_saved, name='success_saved'),
    path('<int:Blog_id>/update', views.Update.as_view(), name='update'),
    path('<int:Blog_id>/delete', views.Delete.as_view(), name='delete'),
]

blogs/models.py
from django.utils import timezone
import datetime
from django.db import models


class Blog(models.Model):
    DoesNotExist = None
    title = models.CharField(max_length=200)
    task = models.TextField()
    pub_date = models.DateTimeField(default=timezone.now(), verbose_name="Time published")
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'/blogs/{self.id}'

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

blogs/forms.py
from django.forms import ModelForm, TextInput, Textarea
from .models import Blog


class CreateForm(ModelForm):
   class Meta:
       model = Blog
       fields = ['title', 'task', 'pub_date', 'image']

       widgets = {
           "title": TextInput(attrs={
               'class': 'form-control',
               'placeholder': 'Название блога'
           }),
           'task': Textarea(attrs={
               'class': 'form-control',
               'placeholder': 'Текст блог'
           }),

    }

blogs/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.template import loader
from django.urls import reverse
from django.views.generic import UpdateView, DeleteView

from .forms import CreateForm
from .models import Blog


def index(request):
    latest_blog_list = Blog.objects.order_by('-pub_date')[:10]
    template = loader.get_template('blogs/Index.html')
    context = {
        'latest_blog_list': latest_blog_list,
    }
    return render(request, 'blogs/index.html', context)


def detail(request, Blog_id):
    try:
        blog = Blog.objects.get(pk=Blog_id)
    except Blog.DoesNotExist:
        raise Http404("Blog does not exist")
    return render(request, 'blogs/detail.html', {'blog': blog})


def create(request):
    error = ''
    if request.method == 'POST':
        form = CreateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blogs:success_saved'))
        else:
            error = 'Wrong form filling'

    form = CreateForm()
    data = {
        'form': form,
        'error': error
    }
    return render(request, 'blogs/create.html', data)


def success_saved(request):
    return render(request, 'blogs/success_saved.html')


class Update(UpdateView):
    model = Blog
    pk_url_kwarg = "Blog_id"
    template_name = 'blogs/update.html'
    form_class = CreateForm


class Delete(DeleteView):
    model = Blog
    pk_url_kwarg = "Blog_id"
    success_url = '/blogs/'
    template_name = 'blogs/delete.html'

blogs/templates/blogs/create.html
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<div class="features">
     <style>
       BODY
       {
        background: linear-gradient(to bottom right,white,red,black) no-repeat;
       }
  </style>
    <h1>
        <p align="center" style="color:DarkRed; font-size:35px">
        Создание Блога
    </h1>
    <form method="post" enctype="multipart/form-data">
        <p align="center" style="margin-top:40px;margin-left:315px;width:900px">
        {% csrf_token %}
        {{ form.title }}<br>
        {{ form.task }}<br>
        {{ form.image }}<br><br>
        {{ form.pub_date }}<br><br>
        <span>{{ error }}</span>
        <button class="btn btn-dark" type="submit">Добавить блог</button>
        <button class="btn btn-dark" style="height:40px;width:120px" onclick="document.location='../'">Back</button>
    </form>
</div>

blogs/templates/blogs/delete.html
<div class="features">
    <h1>
        Удаление блога<br>
        Хотите удалить этот блог?
    </h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Удалить блог</button>
        <button class="btn btn-warning" type="submit">Want удалить</button>
    </form>
</div>

blogs/templates/blogs/detail.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
 <style>
       BODY
       {
        background: url(img/обои.png) no-repeat;
       }
  </style>
<style>
           figure {
                height: 595px;
                margin: 0;
                overflow: hidden;
           }
           figure img {
                width: 100%;
                margin: -10% 0 0 0;
           #glaw {
               display:inline;
               width:880px;
           }
           }
           .blok1, .blok2 {
                border-radius: 4px;
                box-shadow: rgba(0,0,0,1.2) 0px 1px 3px;
           }
           .blok1 {
              float:right;
              width:600px;
              height:660px;
              padding: 5px;
              text-align: center;
              vertical-align: middle;
          }
          .blok2 {
              vertical-align: middle;
              float:left;
              width:900px;
              height:660px;
              padding: 5px;
              text-align: center;
          }
        </style>
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <div id="glaw">
            <div class="blok1">
                <h1>
                    <p align="center" style="color:black; font-size:30px">
                    {{ blog.title }}
                </h1>
                    <div align="right">
                    <figure>
                        <p vertical-align="middle"></p>
                        <img src="{{ blog.image.url }}">
                    </figure>
                    </div>
            </div>
            <div class="blok2">
                    <div align="left" style="color:black; font-size:20px">
                        {{ blog.task }}
                    </div>
                    <p align="right" style="color:FFCCCC; font-size:20px">
                    Was published: {{ blog.pub_date }}
            </div><br>
                <h3>
                    <p align="center" style="margin-top: 640px">
                    <button class="btn btn-dark" style="width:350px" onclick="document.location='../'"><---Back to Blogs</button>
                    <button class="btn btn-dark" style="width:350px" onclick="document.location='update'">Update blog</button>
                    <button class="btn btn-dark" style="width:350px" onclick="document.location='delete'">Delete blog</button>
                </h3>
        </div>

blogs/templates/blogs/index.html
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<div class="INDEX">
    <style>
       BODY
       {
        background: linear-gradient(to bottom right,white,red,black) no-repeat;
       }
  </style>
     <h1>
        <p align="center" style="color:#DC143C; font-size:35px">
        Blogs list
    </h1>
     <h2>
        {% if latest_blog_list %}
            <ul>
            {% for blog in latest_blog_list %}
               <p align="left" style="color:DarkRed; font-size:35px">
               <p><li><a href="{% url 'blogs:detail' blog.id %}"style="color:DarkRed">{{ blog.title }}<br></a></li></p>
            {% endfor %}
            </ul>
        {% else %}
             <p>No blogs are available.</p>
        {% endif %}
     </h2>
    <h4>
<button class="btn btn-dark" style="height:40px;width:120px" onclick="document.location='create'">Create blog</button>
<button class="btn btn-dark" style="height:40px;width:120px" onclick="document.location='../'">Back</button>
    </h4>
</div>

blogs/templates/blogs/success_saved.html
  <style>
       BODY
       {
        background: white;
       }
  </style>
<div class="features">
    <h1>
        Your blog has been successfully saved.<br>
        Congratulations.
    </h1>
    <h2>
        <button class="btn btn-outline-warning" style="height:50px;width:200px" onclick="document.location='../blogs/'">To blogs</button>
    </h2>
   </div>

blogs/templates/blogs/update.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<div class="features">

    <h1>
          <p align="center" style="color:DarkRed; font-size:35px">
        Редактирование Блога

    </h1>
    <style>
       BODY
       {
        background: linear-gradient(to bottom right,white,red,black) no-repeat;
       }

  </style>
    <form method="post" enctype="multipart/form-data">
        <p align="center" style="margin-top:40px;margin-left:315px;width:900px">
        {% csrf_token %}
        {{ form.title }}<br>
        {{ form.task }}<br>
        {{ form.image }}<br><br>
        {{ form.pub_date }}<br><br>
        <span>{{ error }}</span>
        <button class="btn btn-dark" onclick="document.location='../'" type="submit">Изменить блог</button>
    </form>
</div>